apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-event-exporter
    helm:
      valuesObject:
        config:
          logLevel: info
          receivers:
            - name: dump
              stdout: {}
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.2.15
