apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server-app.yaml
  - ingress-nginx-app.yaml
  - sealed-secrets-app.yaml
  - rook-ceph-app.yaml
  - promtail-app.yaml
  - kubernetes-event-exporter-app.yaml
