apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: Replace=true
resources:
  - metrics-server-app.yaml
  - ingress-nginx-app.yaml
  - sealed-secrets-app.yaml
  - rook-ceph-app.yaml
  - promtail-app.yaml
  - kubernetes-event-exporter-app.yaml
  - kubelet-csr-approver-app.yaml
  - cert-manager-app.yaml
  - kube-prometheus-stack-app.yaml
