apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rook-ceph
    helm:
      valuesObject:
        csi:
          enableCephfsDriver: false
          enableCephfsSnapshotter: false
          enableNFSSnapshotter: false
          enableRBDSnapshotter: false
          provisionerReplicas: 1
          provisionerTolerations:
            - operator: Exists
              effect: NoSchedule
          provisionerNodeAffinity: node-role.kubernetes.io/control-plane=
          pluginTolerations:
            - operator: Exists
              effect: NoSchedule
    repoURL: https://charts.rook.io/release
    targetRevision: 1.15.5
